# Generated by Django 4.0.1 on 2022-02-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_interest_item_itemtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
