# Generated by Django 4.0.1 on 2022-02-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
