# Generated by Django 4.0.1 on 2022-02-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_user_user_id_delete_customer_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=50)),
                ('fathermobile', models.BigIntegerField()),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('dob', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('idproof', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('facebookurl', models.CharField(max_length=70)),
                ('twitterurl', models.CharField(max_length=70)),
                ('instagramurl', models.CharField(max_length=70)),
                ('linkedinurl', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.customer')),
            ],
        ),
    ]
