# Generated by Django 4.0.1 on 2022-03-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
