# Generated by Django 4.0.1 on 2022-03-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_delete_item_delete_itemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemtype', models.CharField(max_length=50)),
            ],
        ),
    ]
