# Generated by Django 4.0.1 on 2022-03-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_delete_customer_delete_itemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=50)),
                ('fathermobile', models.BigIntegerField()),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('dob', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('idproof', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('status', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='itemgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemgroup', models.CharField(max_length=50)),
                ('status', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
    ]
