# Generated by Django 4.0.1 on 2022-03-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_customer_itemgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('status', models.CharField(default=None, max_length=30, null=True)),
                ('itemtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgroup')),
            ],
        ),
        migrations.DeleteModel(
            name='interest',
        ),
    ]
