# Generated by Django 4.0.1 on 2022-03-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_item_delete_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
        migrations.DeleteModel(
            name='itemgroup',
        ),
    ]
