# Generated by Django 4.0.1 on 2022-03-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_itemgroup_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
