# Generated by Django 4.0.1 on 2022-03-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemgroup', models.CharField(max_length=100)),
                ('status', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
    ]
