# Generated by Django 4.0.1 on 2022-03-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
