# Generated by Django 4.0.1 on 2022-03-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.CharField(max_length=500)),
                ('status', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
    ]
