# Generated by Django 4.0.1 on 2022-03-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_loanitem_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loanitem',
        ),
    ]
