# Generated by Django 4.0.1 on 2022-03-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_loanitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.adminlogin')),
            ],
        ),
    ]
