# Generated by Django 4.0.1 on 2022-04-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanitem',
            name='loanid',
        ),
        migrations.DeleteModel(
            name='loan',
        ),
        migrations.DeleteModel(
            name='loanitem',
        ),
    ]
