# Generated by Django 4.0.1 on 2022-04-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_remove_loanitem_loanid_delete_loan_delete_loanitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loandate', models.CharField(max_length=50)),
                ('customername', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('qty', models.CharField(max_length=40)),
                ('grossweight', models.CharField(max_length=40)),
                ('netweight', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=100)),
                ('loanamount', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=40)),
                ('advancepaid', models.CharField(max_length=40)),
                ('processingfees', models.CharField(max_length=40)),
                ('installments', models.CharField(max_length=40)),
                ('netpayable', models.CharField(max_length=100)),
                ('maturitydate', models.CharField(max_length=40)),
                ('paymentmode', models.CharField(max_length=40)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='loanitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemgroup', models.CharField(max_length=40)),
                ('itemname', models.CharField(max_length=40)),
                ('qty', models.CharField(max_length=40)),
                ('grossweight', models.CharField(max_length=40)),
                ('netweight', models.CharField(max_length=40)),
                ('purity', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=40)),
                ('loanid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.loan')),
            ],
        ),
    ]
