# Generated by Django 4.0.1 on 2022-04-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_loan_loanitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='payinterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loannumber', models.CharField(max_length=40)),
                ('customername', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(max_length=40)),
                ('intereststartdate', models.CharField(max_length=40)),
                ('interestcoveredtill', models.CharField(max_length=40)),
                ('monthsremaining', models.CharField(max_length=30)),
                ('totalinterestamount', models.CharField(max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.customer')),
            ],
        ),
    ]
